#!/bin/bash

for i in $(dirname $0)/*.ts $(dirname $0)/*/;
do
    echo "start testing $i"
    ts-node "$i";
    exit_code="$?"
    if [ "$exit_code" -ne 0 ];
    then
        echo "$i test failed"
        exit $exit_code
    fi
    echo "$i success"
done

echo "all test pass"
